---
- name: Pull and Run docker image of akshaynagpal22/ai_on_the_edge
  hosts: all
  tasks:
    - name: Pull akshaynagpal22/ai_on_the_edge
      docker_image:
        name: akshaynagpal22/ai_on_the_edge
        source: pull
    - name: Create default containers
      shell:
        cmd: docker run -itd --privileged -p 8088:8080 -p 8090:5672 -e HIBERNATE_MYSQL_URL=192.168.29.132:8085 --name platform akshaynagpal22/ai_on_the_edge
    - name: Running commands
      shell:
        cmd: docker exec -it platform bash mount 192.168.29.132:/mnt/nfs_share/ /./mnt/nfs_share/ && service rabbitmq-server start && rabbitmqctl add_user test test && rabbitmqctl set_user_tags test administrator && rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
#      docker_container:
#        name: platform
#        image: akshaynagpal22/ai_on_the_edge
#        privileged: yes
#        state: started
#        ports:
#          - "8088:8080"
#          - "8090:5672"
#        env:
#          HIBERNATE_MYSQL_URL: "192.168.29.132:8085"

#        command: mount 192.168.29.132:/mnt/nfs_share/ /./mnt/nfs_share/ && service rabbitmq-server start && rabbitmqctl add_user test test && rabbitmqctl set_user_tags test administrator && rabbitmqctl set_permissions -p / test ".*" ".*" ".*"